### ISSUE TITLE
[導入] 誰を助けるために作るのか

### ISSUE THREAD

**Issue by HomMarkHunt** [javamas/araignee#1]
# アレニエは誰を助けるために作るのか。
## 概要

要求の中で、**育児** を助けるとしたが、
育児に関わる**誰？**に使って欲しいのか。母子家庭の家族か、核家族か、母親か...
ターゲットを決める。
## 担当

@nayuta28 @char-miki-tty @ta-chibana

**Comment by HomMarkHunt** [comment]
候補として

`対象多`
- 子供がいる家庭(家族構成は問わない)
- 父母
- 母親のみ
- (母子家庭の)母親のみ

`対象少`

かなと思いました。

対象多いところを選ぶと範囲が広くなる。
対象少ないところを選ぶと範囲が狭くなる。

ので

> 母親のみ
> がちょうどいいかな？

**Comment by char-miki-tty** [comment]
父親のみはない？

**Comment by nayuta28** [comment]
- 母親のみ
- (母子家庭の)母親のみ
  この２つの違いって何？？

**Comment by ta-chibana** [comment]
母子家庭じゃないと受け取れない手当も収集する対象に含めるかどうかとか

**Comment by nayuta28** [comment]
あ！そういうことか！理解しました。

**Comment by ta-chibana** [comment]
> 父親のみはない？
- 母子家庭
- 父子家庭

この２つでもらえる手当にあまり違いがなければ、どちらも対象にしちゃって良いかなーという気もします！

**Comment by char-miki-tty** [comment]
母子家庭か父子家庭かというより収入の違いじゃないかなぁーと思った。
手当に違いが出るかどうかは調べないと分からないけど、どちらも対象で良いのでは？

**Comment by char-miki-tty** [comment]
あ、うそ！サポートの種類が違うって！
母子家庭の場合には、生活費など経済的な面で、父子家庭の場合には、家事・育児などの生活面で困るという違いがあります。
ですって。

**Comment by nayuta28** [comment]
> 母子家庭の場合には、生活費など経済的な面で、父子家庭の場合には、家事・育児などの生活面で困るという違いがあります。

これってどこソース？なんか考え方が古い気が・・・

**Comment by ta-chibana** [comment]
収入による違いはありますよね

> 母子家庭の場合には、生活費など経済的な面で、父子家庭の場合には、家事・育児などの生活面で困るという違いがあります。

という傾向にあります。的な話ではなくて？

http://www.mhlw.go.jp/bunya/kodomo/osirase/dl/100526-1b.pdf では、
**平成２２年８月１日から、父子家庭のみなさまにも児童扶養手当が支給されます！**
とあるので、昔は違いがあって、もしかしたら今も多少は違いがあったりするのかも。。

**Comment by char-miki-tty** [comment]
そう！傾向の話！
この辺の考えは地域によって差がでると思われる。
女は家庭を守るものだ的な思想は九州では普通にあるぞ。

**Comment by nayuta28** [comment]
候補を
- (母子家庭の)母親のみ

ではなくて、
- 片親のみ

としておいて、ここをターゲットとするならそこから母子家庭・父子家庭での違いを調べてみることでスコープを更に絞るかどうかの検討をしてみるとか

**Comment by ta-chibana** [comment]
> この２つでもらえる手当にあまり違いがなければ、どちらも対象にしちゃって良いかなーという気もします！

こんなこと言っといてあれですが、
- 母子家庭・父子家庭に違いがある場合
  - どちらか片方にとっては余計な情報が混ざることになり、片方に特化できない
- 母子家庭・父子家庭に違いがない場合
  - どちらかをターゲットにすれば、自然ともう片方に必要な情報も網羅できる？

**Comment by HomMarkHunt** [comment]
ちなみに範囲とかアプリのことは一回忘れたら、一番助けたい層はどこですか？

私は
- 母親

を助けたい！

**Comment by char-miki-tty** [comment]
母親にしましょう

**Comment by ta-chibana** [comment]
> 母子家庭・父子家庭での違いを調べてみることでスコープを更に絞るかどうかの検討をしてみるとか

私も同意です。しかし非常に #2 と絡み合ってくる展開が予想されますね。

**Comment by ta-chibana** [comment]
> ちなみに範囲とかアプリのことは一回忘れたら、一番助けたい層はどこですか？

確かに難しいこと考えずにこれで良さそうだ！

**Comment by dodoichi** [comment]
育児を援助するのは、親のためなのかな？

**Comment by nayuta28** [comment]
育児支援の本来の目的は親ではなく子供のため
↓
子供のことを一番真剣に考えて助けたいと思ってるのは親
↓
そんな子供のためを思っている親を助けたい
↓
アレニエ

という風に考えました。

**Comment by HomMarkHunt** [comment]
@nayuta28 に同意です。
親だと補助金の範囲が広いのでその中でも母親(父親も？)。
というのに落ち着きそうですかね？

**Comment by ta-chibana** [comment]
親への金銭的な援助は子を助けると思っています！

**Comment by dodoichi** [comment]
対象は低所得家庭で開始。
