### ISSUE TITLE
パーツを選定する

### ISSUE THREAD

**Issue by dodoichi** [javamas/araignee#11]
自作PCパーツを選定しましょう。

どの部品も複数候補を挙げた上で、スペックと予算を天秤にかけて決めましょう。

依存性、相性があるので、後で泣かないように調査すること。
例えば、あるマザーボードにはこのCPUは載せられないとか、このケースにあのファンは大きすぎるとか。買ってからでは後の祭りです。

コメントで決めていって、最後に下のテーブルにまとめましょう。
担当は一応隊長にしときますが、みんなで意見を出し合って、ガンガン希望を述べるのが楽しいと思います。

| 部品 | 製品 | 購入希望価格 | 備考 |
| --- | --- | --- | --- |
| マザーボード |  |  | 大きさを考えないと、ケースに入らない |
| CPU |  |  | 4コア以上は欲しいかな |
| DISK |  |  | HDD/SSD |
| Memory |  |  | 1枚あたりのサイズ x 枚数 |
| ファン |  |  | 空冷だよね？ |
| ケース |  |  | 他のパーツの大きさを考慮する |

**Comment by dodoichi** [comment]
色々書きましたが、そんなに高いスペックを用意しなくてもよいです。
自作を体験するのが目的なので。
（スペックが必要になったらクラウド使うし…）

**Comment by HomMarkHunt** [comment]
そんなにスペックいらないとしたら
- メモリ 4G*2
- HDD 512G(256Gでもいいかな？)

みたいなノートパソコンみたいなスペックで良いのかな。

**Comment by char-miki-tty** [comment]
確かに体験用として使う分にはそのぐらいのスペックで良い気がする。

**Comment by char-miki-tty** [comment]
ちょっと話逸れますが・・・
自作PCの話はどんな流れで出てきたんですか？
確か自分がいない時に出た話でしたよね。
皆さんはPC自作するにあたって、何か目的とかあったりします？

**Comment by char-miki-tty** [comment]
CPU選ぶのに参考になるかな・・・
http://life-hacking.net/%E3%80%902016%E3%80%91cpu%E5%BE%B9%E5%BA%95%E6%AF%94%E8%BC%83%EF%BC%81%E7%A8%AE%E9%A1%9E%E3%83%BB%E3%82%B9%E3%83%9A%E3%83%83%E3%82%AF%E3%83%BB%E6%80%A7%E8%83%BD%E5%B7%AE%E3%81%AF%EF%BC%9F%E5%8B%95/

**Comment by disc99** [comment]
誰かの家でサーバを起動しておくなら、ファンは静かで、消費電力は少なめにしとくといいと思うよ！
その方が家庭に優しいサーバになる 🐼

**Comment by HomMarkHunt** [comment]
@char-miki-tty 

> 自作PCの話はどんな流れで出てきたんですか？

PC自作の話は特に前触れもなく出てきましたね！単純にやったら楽しそうだよね！的な

> 皆さんはPC自作するにあたって、何か目的とかあったりします？

*以前やったら画面すらつかなかったんで、ちゃんと起動して使える状態のものを作りたい
- みんなでワイワイ組み立てたら楽しそう
- 低レイヤ(ハードウェア)をやってみたくて、組むのはいい勉強になると思ったから
- 楽しそう

が、私の中での目的です！

**Comment by char-miki-tty** [comment]
@disc99 
音や消費電力の事は全く考えていませんでした！笑
🐼 さんアドバイスありがとうございます！！

@HomMarkHunt 
なるほど！そんなに本格的にやろうって感じじゃなかったんですね。まぁ最初ですしね・・・
ちなみに以前やって起動しなかった原因とか分かりますか？
もし失敗談とかあれば参考にしたいです！！

とりあえず楽しい感じで進めましょう:bear:
今日中に自分が調べたパーツ候補出しますね〜:bear:

**Comment by char-miki-tty** [comment]
AMDのCPUってネットでは
安いし、自作で使う分には問題なく使える！初めての人にはオススメ〜
というような記事が結構あるのですが、実際に使った事ある方いますか？

@HomMarkHunt は以前やった時は何を使いましたか？

**Comment by char-miki-tty** [comment]
Amazonのよく一緒に購入されている商品を追っていった結果

マザーボード
http://www.amazon.co.jp/ASUSTeK-H170%E6%90%AD%E8%BC%89-%E7%AC%AC6%E4%B8%96%E4%BB%A3%E3%82%A4%E3%83%B3%E3%83%86%E3%83%AB%E3%83%97%E3%83%AD%E3%82%BB%E3%83%83%E3%82%B5%E3%83%BC%E5%AF%BE%E5%BF%9C-%E3%83%9E%E3%82%B6%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89-H170-PRO/dp/B013HIDM3I/ref=pd_bxgy_147_2?ie=UTF8&refRID=1ZJ2FTGQMGNF9KFKCBRR

CPU
http://www.amazon.co.jp/exec/obidos/ASIN/B0136JOMXC/cvtnl0010e-22/ref=nosim/

メモリ
http://www.amazon.co.jp/CFD-Panram-%E3%83%87%E3%82%B9%E3%82%AF%E3%83%88%E3%83%83%E3%83%97%E7%94%A8-DDR4-PC4-17000-W4U2133PS-4G/dp/B0162L30IO/ref=pd_sim_147_1?ie=UTF8&dpID=51lyQl7GRML&dpSrc=sims&preST=_AC_UL160_SR160%2C160_&refRID=1ZJ2FTGQMGNF9KFKCBRR

ファン
http://www.amazon.co.jp/%E3%82%B5%E3%82%A4%E3%82%BA-%E3%80%90HASWELL%E5%AF%BE%E5%BF%9C%E3%80%91-%E8%99%8E%E5%BE%B9-12cm%E3%82%B5%E3%82%A4%E3%83%89%E3%83%95%E3%83%AD%E3%83%BC-SCKTT-1000/dp/B00G1YXN6M/ref=pd_bxgy_147_3?ie=UTF8&refRID=0J1ZWDA9400T9JMTF0R3

ケース
http://www.amazon.co.jp/dp/B00Z1MYMPQ?psc=1

**Comment by dodoichi** [comment]
まず、CPUを絞りましょう。
マザボは、それによって絞られるので。
上のCPUはデスクトップ向けだと思いますが、新しくてスペックもそこそこなので、よいかな。

メモリは4GBx2でよいですが、後で拡張できるようにマザボのスロットの数とスロットごとの限界を見ておく必要があります。あと、CPUによって認識しない場合があるようなので、気をつけて。

ファンは口コミからうるさいものを避ける。

ケースはマザボのサイズに合わせる。

こんな感じかな。

**Comment by char-miki-tty** [comment]
@dodoichi 
そうか、デスクトップ用とかあるのですね・・・
とりあえず4コアで探したのですが、たくさんありすぎて判断出来なかったのでAmazon評価に頼ってしまいました・・・
スペックが問題なければ自分はこのCPUで良いかなと思ってます！:bear:

仮にこのCPUで進める場合・・・

**CPU**
- Memory Type:DDR4/DDR3L

**マザーボード**
- メモリ:4×DIMM DDR4 2133(最大64GB)

このように書かれていた場合

メモリは【DDR4】を使用すれば問題ないと判断しても良いのでしょうか？

またマザーボードのスロット数とスロット毎の限界というのはこの表記だと
- スロット数 → 4
- スロット毎の限界 → 16

となりますか？

ちなみに参考にしたサイトが複数あって、大体どのサイトもパーツを選ぶ順番はこんな感じでした↓
1. ＣＰＵ 
2. マザーボード
3. メモリ
4. DISK
5. ファン
6. ＰＣケース
7. 電源
8. OS

Amazonのよく一緒に購入されている商品を追っていった結果は
一応この順番で追っていきました。笑
（ハードディスクは飛ばしてますが・・・）

皆さんCPUを先に決めましょう！
もうちょい安いのが良いとか、もっとスペック欲しいとか、何か意見があればコメントして下さい〜:bear:

**Comment by HomMarkHunt** [comment]
@char-miki-tty 

> ちなみに以前やって起動しなかった原因とか分かりますか？

これは全くわかりません！
恐ろしくわかりません！
電源ボタン押してもなにもなかったのでもうわからん！ってなっちゃいました！

> 以前やった時は何を使いましたか？

以前自作したときは友達にもらったintelのセレロン(スペルわからん)でした！
友人に「これ化石だけどいいの？」って渡されたの覚えてます！

**Comment by HomMarkHunt** [comment]
<img src='https://cloud.githubusercontent.com/assets/14356345/14987208/07700b5e-118a-11e6-985c-42dedca17fa0.png' width='180'/>

AMDのFXシリーズがintelのiシリーズと比べて複数アプリケーション起動に強く、DBとかに向いてるとのこと！
またintelより価格も安いです！

| モデル名 | 周波数 | TB | コア数 | スレッド数 | LLC | TDP | amazon | 値段 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 8320E | 3.2GHz | 4.0GHz | 8 | 8 | 8MB | 95W | http://www.amazon.co.jp/exec/obidos/ASIN/B00MUTWEM6/cvtnl0010e-22/ref=nosim/ | 18,834 |
| 6300 | 3.5GHz | 4.1GHz | 6 | 6 | 8MB | 95W | http://www.amazon.co.jp/exec/obidos/ASIN/B009O7YORK/cvtnl0010e-22/ref=nosim/ | 13,910 |
| 4300 | 3.8GHz | 4.0GHz | 4 | 4 | 4MB | 95W | http://www.amazon.co.jp/exec/obidos/ASIN/B009O7YU3S/cvtnl0010e-22/ref=nosim/ | 12,434 |

**Comment by char-miki-tty** [comment]
> AMDのFXシリーズがintelのiシリーズと比べて複数アプリケーション起動に強く、DBとかに向いてるとのこと！

なるほど！今回の用途にはこっちの方が合ってるかな？
価格も安いしね！:bear:

**Comment by HomMarkHunt** [comment]
### マザボの選び方

仮に 上記のAMD FXシリーズにしたとすると、チップセット(マザーボード上に搭載されている基盤的なの)もAMD製にする必要があります。

その対応チップセットが、FXシリーズの場合は
[AMD900番台](https://www.pc-koubou.jp/blog/amd_chipset_reference.php#amd9) のチップセットにする必要があります。
(仮にCPUをIntelにしたら、原則Intel製のチップセットにする必要がある。)

つまり **AMD900番台のチップセットが搭載されているマザーボード** を買う必要があるということです。
900番台には3種類あるので
1. メモリのスロット数などでチップセットを決める。
1. そのチップセットが搭載されているマザボを選ぶ。

という手順が必要になります。(たぶん)

なお、上記シリーズには **ファンがついてくる** ポイことが書かれてますが、すみません調べ切れていません...

### マザボの参考画像

![image](https://cloud.githubusercontent.com/assets/14356345/15348196/8f79b494-1d03-11e6-8144-6923fb098843.png)

**Comment by HomMarkHunt** [comment]
というわけで、私はCPUは [こちら](http://www.amazon.co.jp/exec/obidos/ASIN/B009O7YORK/cvtnl0010e-22/ref=nosim/) のAMD FX-6300がいいと思います。

理由として
- Intelに比べ値段が安い(同スペックだと1万数千円違う)
- 6coreもある
- ネットに**めっちゃ早いって書いてあった**

です。

**Comment by char-miki-tty** [comment]
@HomMarkHunt さんありがとうございます！！めちゃくちゃ分かりやすい！:bear:
私もAMDのCPUが良いと思います！！

### マザーボード

[ここ](http://matari23.blog.fc2.com/blog-entry-1172.html)にオススメマザーボード比較表がありました。

■ AMD 990FX搭載マザーボード

| マザーボード製品名 | 価格 | メモリ | 規格 |
| --- | --- | --- | --- |
| [ASRock 990FX Extreme9](http://matari23.blog.fc2.com/blog-entry-3348.html) | 29,000円 | メモリスロット数4個、最大メモリ容量64GB | ATX、DDR3-1600、PCI-E 2.0 x16、USB 3.0、USB 2.0 |
| [GIGABYTE GA-990FXA-D3](http://matari23.blog.fc2.com/blog-entry-1085.html) | 8,000円 | メモリスロット数4個、最大メモリ容量32GB | 基本的な機能を持ったATXのマザーボード。 |

■ AMD 970搭載マザーボード

| マザーボード製品名 | 価格 | メモリ | 規格 |
| --- | --- | --- | --- |
| [MSI 970A SLI KRAIT EDITION](http://matari23.blog.fc2.com/blog-entry-3830.html) | 13,200円 | スロット数4個、最大メモリ容量32GB | ATX、DDR3-2000、USB3.1等、305x224mm、高耐久 |
| [MSI 970 GAMING](http://matari23.blog.fc2.com/blog-entry-3443.html) | 13,000円 | メモリスロット数4個、最大メモリ容量32GB | ATX、DDR3-1866、USB3.0等、305x244mm、高音質 |
| [ASRock 970A-G/3.1](http://matari23.blog.fc2.com/blog-entry-3983.html) | 11,300円 | メモリスロット数4個、最大メモリ容量64GB | ATX、DDR3-2400+、USB3.1等、高音質 |
| [MSI 970A-G43 PLUS](http://matari23.blog.fc2.com/blog-entry-3847.html) | 10,800円 | メモリスロット数4個、最大メモリ容量32GB | ATX、DDR3-1866、USB3.1等、305x225mm |
| [MSI 970A-G46](http://matari23.blog.fc2.com/blog-entry-3318.html) | 10,000円 | メモリスロット数4個、最大メモリ容量32GB | ATX、DDR3-1866、PCI-E 2.0 x16、USB 3.0、USB 2.0、305x225mm |
| [ASRock 970 Pro3 R2.0](http://www.amazon.co.jp/970%E3%83%81%E3%83%83%E3%83%97%E3%82%BB%E3%83%83%E3%83%88%E6%90%AD%E8%BC%89-ATX%E3%83%9E%E3%82%B6%E3%83%BC%E3%83%9C%E3%83%BC%E3%83%89-970-Pro3-R2-0/dp/B01DJ30NKG/ref=sr_1_6?s=computers&ie=UTF8&qid=1463587693&sr=1-6&keywords=970) | 9,680円 | メモリスロット数4個、最大メモリ容量64GB |  |

ちなみに900番台3種類の違いは拡張スロットの数みたいです

| チップセット | 拡張スロット |
| --- | --- |
| AMD 970 | PCI Express 2.0 x16スロットX 最大 1基 |
| AMD 990X | PCI Express 2.0 x16スロットX 最大 2基 |
| AMD 990FX | PCI Express 2.0 x16スロットX 最大4基 |

**Comment by HomMarkHunt** [comment]
まとめありがとうございます！

> | マザーボード製品名 | 価格 | メモリ | 規格 |
> | --- | --- | --- | --- |
> | [GIGABYTE GA-990FXA-D3](http://matari23.blog.fc2.com/blog-entry-1085.html) | 8,000円 | メモリスロット数4個、最大メモリ容量32GB | 基本的な機能を持ったATXのマザーボード。 |

これ！がいいなと思いました。理由は、
- 値段安い
- サイズが一番メジャーなATX
- スロットいっぱいある
- メモリの要件も満たしている
- 拡張性高

です！

ただ、もう取り扱ってるところが少なそうで...
http://kakaku.com/item/K0000786409/spec/?lid=spec_anchorlink_details#tab
ここで売ってました。バージョン新しいやつかな？

**Comment by char-miki-tty** [comment]
AMD 990FXはやっぱり他の2つより価格が高めみたいですね。

> | マザーボード製品名 | 価格 | メモリ | 規格 |
> | --- | --- | --- | --- |
> | [GIGABYTE GA-990FXA-D3](http://matari23.blog.fc2.com/blog-entry-1085.html) | 8,000円 | メモリスロット数4個、最大メモリ容量32GB | 基本的な機能を持ったATXのマザーボード。 |

Amazonで検索したら2万ぐらいのが多かったので、これはかなり安いです。

> ただ、もう取り扱ってるところが少なそうで...

わ！リンク先ちゃんと見てなかった！すみません！:bear: :sweat_drops:

| マザーボード製品名 | 価格 | メモリ | 規格 |
| --- | --- | --- | --- |
| [990FXA-GD65](http://kakaku.com/item/K0000268692/spec/?lid=spec_anchorlink_details#tab) | 12,350円 | メモリスロット数4個、最大メモリ容量32GB | ATXのマザーボード |

これも良いかも！

**Comment by HomMarkHunt** [comment]
候補に挙がってる二つのマザボの気になったところを比較してみました。
マザボは[ここいわく](http://torano-maki.net/capture/custom/mother_board.html)
- 拡張性
- 機能性

で選ぶようですが、表示スペックではそんなに違いが見られませんでした、が。

| 製品名 | 価格 | 発売日 |
| --- | --- | --- |
| [GA-990FXA-UD3 R5](http://kakaku.com/item/K0000786409/spec/?lid=spec_anchorlink_details#tab) | ¥13,990 | **2015年 5月16日** |
| [990FXA-GD65](http://kakaku.com/item/K0000268692/spec/?lid=spec_anchorlink_details#tab) | ¥12,350 | **2011年 6月28日** |

古いのはなんか嫌ですよね..??

**Comment by char-miki-tty** [comment]
> 古いのはなんか嫌ですよね..??

うむ:bear:

**Comment by HomMarkHunt** [comment]
決まり。。でいいのかな。。？

**Comment by dodoichi** [comment]
メモリ選んだら対応してなかったとかならないように、フルセット候補を挙げてからでないと決められないんじゃないかな？

**Comment by HomMarkHunt** [comment]
あ、すみません！
"マザーボードが" 決まりでいいかな？
という意味でした！

マザーボード決まったらあとはそれに合うメモリとかファンを決めていく。

と、思ってたんですがあってますかね？

**Comment by char-miki-tty** [comment]
@HomMarkHunt さん
自分もそのつもりでした！
1. ＣＰＵ
2. マザーボード
3. メモリ
4. DISK
5. ファン
6. ＰＣケース
7. 電源
8. OS

次はメモリ！

**Comment by dodoichi** [comment]
OSインストールにDVDドライブいらんかな？

**Comment by disc99** [comment]
あれば安心ですが、最近のBIOSはUSBインストール出来るものも多いはずなので、その辺り調べとくといいかもですね！

**Comment by char-miki-tty** [comment]
@dodoichi 🐴 さん

> OSインストールにDVDドライブいらんかな？

PCケース内にDVDドライブを取り付けるということでしょうか？
自分はUSBで繋ぐDVDドライブで良いかなーと思っていました。

@disc99 🐼 さん

> あれば安心ですが、最近のBIOSはUSBインストール出来るものも多いはずなので、その辺り調べとくといいかもですね！

今回の[マザーボード？](http://www.gigabyte.jp/products/product-page.aspx?pid=3894#sp)のBIOSは【AWARD BIOS】でこちらは設定項目にある【First Boot Device】を以下に変更すればCD-ROMでもUSBでもインストール可能みたいです。
- CD-ROMの場合は【CDROM】を選択
- USBメモリの場合は【USB-HDD】を選択

OSインストールの事はまだ考えていませんでした・・・
ご指摘ありがとうございます！:bear:

初期設定の手順も調べておきます！

**Comment by char-miki-tty** [comment]
| 部品 | 製品 | 購入希望価格 | 備考 |
| --- | --- | --- | --- |
| マザーボード | [GA-990FXA-UD3 R5](http://kakaku.com/item/K0000786409/spec/?lid=spec_anchorlink_details#tab) | 13,990 |  |
| CPU | [AMD FX-6300](http://www.amazon.co.jp/exec/obidos/ASIN/B009O7YORK/cvtnl0010e-22/ref=nosim/) | 14,044 |  |
| DISK | [WD WD10EZEX](http://www.amazon.co.jp/%E5%86%85%E8%94%B5%E3%83%8F%E3%83%BC%E3%83%89%E3%83%87%E3%82%A3%E3%82%B9%E3%82%AF-3-5%E3%82%A4%E3%83%B3%E3%83%81-Blue-WD10EZEX-200rpm/dp/B0085PZHXW/ref=lp_2151923051_1_3?s=computers&ie=UTF8&qid=1464171742&sr=1-3) | 6,180 | 3.5インチ 1TB / 7,200rpm / SATA 6Gb/s |
| Memory | [Kingston KVR16N11S8/4/FP5](http://www.amazon.co.jp/%E3%80%90Kingston-%E3%83%87%E3%82%B9%E3%82%AF%E3%83%88%E3%83%83%E3%83%97PC%E5%A2%97%E8%A8%AD%E7%94%A8%E3%83%A1%E3%83%A2%E3%83%AA-%E3%83%95%E3%83%A9%E3%82%B9%E3%83%88%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%83%95%E3%83%AA%E3%83%BC%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8-KVR16N11S8-FP5/dp/B00D1Q4PKG/ref=sr_1_5?s=computers&ie=UTF8&qid=1464107669&sr=1-5&keywords=%E3%83%A1%E3%83%A2%E3%83%AA) | 3,960 | 4GB x 2 |
| ファン | [虎徹 SCKTT-1000](http://www.amazon.co.jp/%E3%82%B5%E3%82%A4%E3%82%BA-%E3%80%90HASWELL%E5%AF%BE%E5%BF%9C%E3%80%91-%E8%99%8E%E5%BE%B9-12cm%E3%82%B5%E3%82%A4%E3%83%89%E3%83%95%E3%83%AD%E3%83%BC-SCKTT-1000/dp/B00G1YXN6M/ref=sr_1_2?s=computers&ie=UTF8&qid=1464178047&sr=1-2) | 3,280 | PCケースに付属しているので必要ないかも？ |
| ケース | [Sharkoon SHA-VS4-WBK](http://www.amazon.co.jp/gp/product/B00QQ4NF24/ref=s9_acsd_ri_bw_rw_PCPCCASE_p1_t?pf_rd_m=AN1VRQENFRJN5&pf_rd_s=merchandised-search-3&pf_rd_r=15K0411SCK2Y65C3MM4Q&pf_rd_t=101&pf_rd_p=220103709&pf_rd_i=2151903051) | 5,321 | ケースは安いので！ |
| 電源 | [玄人志向 KRPW-L5-600W/80+](http://www.amazon.co.jp/%E7%8E%84%E4%BA%BA%E5%BF%97%E5%90%91-STANDARD%E3%82%B7%E3%83%AA%E3%83%BC%E3%82%BA-80-ATX%E9%9B%BB%E6%BA%90-KRPW-L5-600W/dp/B010SSD9NS/ref=sr_1_6?s=computers&ie=UTF8&qid=1464178426&sr=1-6) | 5,840 |  |
| OS | CentOS |  |  |

**Comment by char-miki-tty** [comment]
パーツ候補一通り選びました〜:bear:
マザボとCPUはネットで既に購入済みです。
他のパーツは土曜日の午前中に買いに行きます。
実際に見てみて別のパーツにする可能性があります。

**Comment by disc99** [comment]
[![LGTM](http://lgtm.in/p/QgxGM3yVp)](http://lgtm.in/i/QgxGM3yVp)

**Comment by HomMarkHunt** [comment]
![LGTM](http://lgtm.in/p/u7MHHIa0q)

**Comment by dodoichi** [comment]
![LGTM](http://lgtm.in/p/oyl2NiELn)
