### ISSUE TITLE
Wikiの運用について考える

### ISSUE THREAD

**Issue by dodoichi** [javamas/araignee#12]
## 何を書くか？

Wikiに書くもの、markdownレポジトリに書き溜めるものの区別をつける必要がある。
順不同で書きだしてみる。
- [ ] 我々は誰か？
  - Organization (Team)
    Javamas
- [ ] ~~役割について~~
  各担当
- [ ] 対象プロジェクト
  Araignee
- [x] Versionについて
  0.1.0 Atypus kaarschi
  マイルストーンと一致
- [ ] ~~Documentationについて~~
  今ここで書いていること
- [ ] 開発の進め方
  - [ ] 開発プロセスについて
  - [ ] 要求、要件、仕様
  - [ ] コードの管理について
  - [ ] Repositoryについて
  - [ ] Code Reviewについて
    - 進め方
  - [ ] Testについて
    - 種類
    - Test Caseの管理
  - [x] Buildについて
    - Management Tool (e.g. Maven)
    - CI
- [x] 環境について
  - Hardware
  - Software
    - Java version
    - CI Tool
      - CheckStyle
      - FindBugs
    - Testing Library
- [x] 運用について
  - 実行について
  - Releaseについて
  - 監視について
  - 障害について
- [ ] BTS
  - Issue作成方法
    - commit message
- [x] ナレッジの蓄積
  - Tips
  - 調査した結果判明したこと
- [ ] 計画について
  スケジュール
## 何故書くか？

書くと決めたものについては、その目的をWikiに明記する。
## どのように書くのか？

熟考して書くよりも、気ままに編集して廃れさせない事のほうが重要。
書くと決めたものについては、マメに更新する。
## 誰が書くのか？

担当機能や作業については、おもに担当者が書く。
Tipsや面白ネタなどは思いついたら書く。
Slackでいいのではという話もある。
## どこに…

あまりガチガチに決めずに、なんとなくこの辺かなという書き方で良いと思う。
Wikiなので、ページを再構成するのは簡単なはず。リンク切れは手当ての必要がありそうだが。

**Comment by dodoichi** [comment]
@javamas/javamas-admins 
直近で必要そうなページの枠だけ作ってみました。
各機能のページはサンプルで、「この書式で書いてね」というつもりではありません。

ガッツリ設計ドキュメントを書くというより、考えを整理するためのメモとして利用してください。

**Comment by HomMarkHunt** [comment]
ありがとうございます！すごい！！なんか感動してしまった！

一つだけ質問が！

> 何を書くか？
> に箇条書きでまとめていただいた項目はかける人が随時埋めて行くということでしょうか？

**Comment by dodoichi** [comment]
書ける人が書くでよいと思います。

ここに挙げたものを全部書くつもりではなく、これから絞り込みますが。

**Comment by ta-chibana** [comment]
大丈夫なのでclose
