### ISSUE TITLE
アーキテクチャについて考える

### ISSUE THREAD

**Issue by dodoichi** [javamas/araignee#13]
各機能は担当者が頑張るので、全体のアーキテクチャを示して助けとする。

特に、機能間での連携方法は選択肢を示すことで、考える幅を広げる。

**Comment by dodoichi** [comment]
コンポーネント図をかいてみた。

<img src="http://plantuml.com/plantuml/png/NL5DRuCm3BtdLrZSuGViK6cYXqrgftRiDksG1KEZXXWbOHAQzj-N16Y0I-9dFtyzE-aKmhFXKYD2ILrF6hM3e-IjuHrZFHTttY9a9Ic5mf79u9S1VBuurqEff6T_JRXJSE76eeduOgWUH01_gSY7uTesP3fSofIaxT3DEQlm9kr4l7vadAb65Udls9ELVgHnmtuZ9nlvu2ymS9XGDDIGlMg7HgCBbEGjmxTqkKP-pHt_vjPNFO_LzJJpRs7tGc7ZYWCijIPllbDcWo0tihsv_B2JQuDMfAHXCg7mFJEBkeOEhVKRPzEquPc21WNA7rp5ayh9NFNPwBv1aFjumyFTHpR_qRUSONs4iFpaVXeixaD7BsL5Wn78aXbhHMbPEbJSebB-dly0">

**Comment by disc99** [comment]
私の当初の理解だと、MQはバッチを起動するためのトリガーとして使うイメージでしたが、このコンポーネント図からいくと、パースしたデータもMQで受け渡す方向ですか？

**Comment by dodoichi** [comment]
Cronで制御するならファイルに一度保存することが前提だったんだけど、MQを使うからにはblobでやりとりする方が無駄がないのと、処理成功・失敗時の制御を自前で実装するコストが減るから、データのやりとりもMQに任せる方がよいと思う。

**Comment by dodoichi** [comment]
added link to #21 #18

**Comment by disc99** [comment]
了解しました！
設計的にはそちらのほうが綺麗かもしれないですね。
とういかMQを使ったシステム運用のベストプラクティスを私が把握できてないのもありますがｗ
問題はこのMilestone内にMQの理解と実装までできるかですね。

**Comment by dodoichi** [comment]
概要は示したので、closeします。
