### ISSUE TITLE
DBを選定する

### ISSUE THREAD

**Issue by HomMarkHunt** [javamas/araignee#15]
## 目的

アレニエでデータを保存するためのDBに何を使うか選定する。

 #6 の関連チケットである
## 選定方法

基本的にはどう選んだらいいか**まったくわからない**。

現場の人に聞いてみたところ、本番稼動のDBを選定するときは
- 利用料金がどれだけ発生するのか
- 想定されるトランザクション量はどの程度なのか

などを考慮する模様。
## 今考えていること
- 金額は基本的に無料がいい
- トランザクション量はかなり少ない(拡張する前なら)
### RDBかNoSQLか
- NoSQLノウハウがない
- 動いたところであまり理解できずDBがブラックボックスになってしまう気がする
- (便利ライブラリ無しでJavaから接続できる自信がない)
- RBDではいけない理由が今のところない
### 選定

上記から、無料で使えるRDB、かつノウハウのあるもの
- PostgresSQL
- MySQL(MariaDB)

のどちらかを対象にしようかと考えています。
## お願い

@dodoichi 
@disc99 

こんな感じで考えてみました。いかがでしょうか？

**Comment by to4iki** [comment]
👍

**Comment by dodoichi** [comment]
いいと思います。

@desc99
MQの永続化にDB使うケースがあるか、確認してみて欲しいな。もし使うなら、別々に立てるのは大仰なので。

**Comment by disc99** [comment]
時間も限られてるので、無理に新しいものに手を出して中途半端になるより、今知っているものを深めるのはいいと思う！

別に時間のあるときに、どんな種類のDB、NoSQLがあるかとか、どんな特性があるかを概要レベルでいいから調べておくと、次回のチャンスに活かせるかもね！

実際、僕もMQ自体は概要くらいしか知らなかったけど、この機会に試してみようと思っているところ！

@dodoichi 
MQの実装によっても違うので、具体的なところまでは落とせていないのですが、今の感覚でいうとRabbitMQ辺りがいいのではと思っていて、となるとインメモリが基本なのでひとまずDBは無くても大丈夫です！

**Comment by HomMarkHunt** [comment]
お二人本当にありがとうございます！

> 別に時間のあるときに、どんな種類のDB、NoSQLがあるかとか、どんな特性があるかを概要レベルでいいから調べておくと、次回のチャンスに活かせるかもね！

たしかに！
Posgre, MySQLは比較のためにいろいろ調べていますが。折角なので(出来る範囲で)ほかも調査してみようと思います！

**Comment by HomMarkHunt** [comment]
# DB検討案

## 検討対象

### RelationalDB

#### MySQL
- Oracle
- 世界シェア82%
1. 命名規則 : 表明に先頭に半角数字を設定できる
2. [チェック制約](https://technet.microsoft.com/ja-jp/library/ms188258%28v=sql.105%29.aspx) : なし、triggerで対応
3. シーケンス : なし
4. オートインクリメント : あり

#### PostgresSQL
- PostgreSQL Global Development Group
- 日本では昔めっちゃ使われてた
1. 命名規則 : 表明に先頭に半角数字を設定できない
2. チェック制約 : あり
3. シーケンス : なし
4. オートインクリメント : あり

### NoSQL

なし

## 検討外

### RelationalDB

#### SQL Server
- Windows
- 管理ツール : SQL Server Management Studio
  - ローカルソフト
- ロックエスカレーションする
  - クエリ発行中にテーブルごとロックするので他の処理に影響が出る
  - 設定でオフれるらしい
- 有料
  - [なんかめっちゃ高かった](https://www.microsoft.com/ja-jp/server-cloud/local/sqlserver/2012/howtobuy/default.aspx)
- ボツ理由:高い、windowsじゃないと..

#### Oracle DB
- Oracle
- 管理ツール : Oracle Enterprise Manager
  - ブラウザソフト
  - 資料が少なく、むずいらしい
- 専門の人が必要なくらい管理がむずい(らしい)
- 有料
  - [引くほど高い](http://www.oracle.com/jp/corporate/pricing/e-pl101005-101005a-n-176288-ja.pdf)
- ボツ理由:高い

### NoSQL

以下全てボツ理由:学習コスト 

#### MongoDB
- 特徴
  - ドキュメント呼ばれるJSONのようなデータ形式を用いる
  - データ集合をコレクションとして扱う
  - コレクションを扱うためにクエリを発行して操作する
- イメージ
  - Jsonとかほぼそのまま保存できる
  - 取り出すの大変そう
- メリット
  - SQL以上の集計クエリ（MS-DocumentDBと並び最強）
  - ロールベースのアクセス管理
  - 大量データの取り扱い
  - リアルタイムでクエリが作成できる
- デメリット
  - トランザクションができない
  - マルチマスタ更新

#### Hadoop
- 特徴
  - データを複数のサーバーで分散してテラバイト、ペタバイト級大容量データを高速に処理できる
    - **そもそもサーバー複数も立て無い**
  - バッチの分散処理が得意
  - 事前にデータを入れる
  - 応答速度より全体の処理を優先する
- イメージ
  - 像
  - 1系と2系で結構違う
  - クラスタ自作すると大変
  - エコプロジェクトめっちゃある
  - 今からHadoop使うことは無さそう
  - SparkならHybe on Tezっていう構成が流行ってる

#### Redis
- 特徴
  - すべてのデータをメモリ上に保持、更新・参照がめちゃハヤ
  - 永続化機構も持っている
- イメージ
  - KVS
  - よく使う
  - がさっと入れてごそっと出す
  - 複雑な検索条件に弱そう
- メリット
  - redis3からシャーディングが可能に
  - 配列に対するPUSH、POPが可能
  - PUB、SUBが可能
  - トランザクションが可能
- デメリット
  - メモリサイズ以上は使えない
  - ディスクへの先行書き込みはできない
  - 自動負荷分散ができない

### その他...
- KVS
  - キーバリュー型... memcached、Oracle Coherence
  - 列指向型ワイドカラムストア... Cassandra、HBASE、Cloud Datastore
- ドキュメント型... Couchbase、MarkLogic、DynamoDB、MS-DocumentDB
- グラフ型... Neo4j

こんなにいっぱい...

**Comment by HomMarkHunt** [comment]
どこにかいていいかわからずここに書いてしまった

**Comment by HomMarkHunt** [comment]
こんな感じで調べたんですが、MySQLとPostgresSQLの検討はどっちがいいか、決定打がなく**全く決められ無い**んですが。

**もうどっちも一緒だから、MySQLでいいんじゃないか。**という投げやりな気持ちも芽生えてきています。

**誰か助けてください。決め手がありません。**
@dodoichi @disc99 @nayuta28 @char-miki-tty @ta-chibana

**Comment by HomMarkHunt** [comment]
使用するDBは、**PostgreSQL**に決定しました。

決定理由としては、
- MySQLとの決定的な差分が見つけられなかった
- であれば開発者の使用経験が多いものに設定する
- 全員使用経験があるのがPostgreSQL

Javaとの接続方法やマイグレーション #26  は別issueにて検討

**Comment by dodoichi** [comment]
![LGTM](http://lgtm.in/p/WJ8b8uHNp)

**Comment by disc99** [comment]
個人的にはPostgreSQL賛成かな！

MySQLとPostgreSQLいつも比較されてるから、ネットで調べて大体知ってると思うけど、自分で何か作るときは、PostgreSQLを使うことが多いね！
理由は標準SQLへの互換性が高いから。

標準をそれなりに理解しているのであればいいけど、そうじゃなきゃ勉強するにも標準に近い方がいいかと思っている。

もちろん業務で使うなら、機能差分を要件をマッチさせたほうがいいけどね！

**Comment by HomMarkHunt** [comment]
@disc99 

コメント、ありがとうございます！

> 標準SQLへの互換性

これもたしかに検討項目に出ていました！

> 機能差分を要件をマッチ

本当はここで検討したかったのですが、アプリケーション構成がふわっとしているのとDBの知識が足りず選ぶことができませんでした。

**Comment by disc99** [comment]
[![LGTM](http://lgtm.in/p/iZGZdY25q)](http://lgtm.in/i/iZGZdY25q)
