### ISSUE TITLE
MQサーバを構築する

### ISSUE THREAD

**Issue by disc99** [javamas/araignee#16]
MQを使用するにあたって、同時にサーバが必要になると思います。
そこで、MQの実装とサーバ構成をどうするかの検討を出来ればと思います。

軽く[まとめ](https://gist.github.com/disc99/e46b0a76cd3285f9142776a15ce578bf)た感じからいくと、プロトタイピングの現時点ではRabbitMQ + SasSのCloudAMQPがいいのではと思っています。
### [CloudAMQP](https://www.cloudamqp.com/)

無料枠で以下が利用出来ます。
Max 1M messages per month
Max 20 concurrent connections
Max 100 queues
Max 10 000 queued messages

将来的に、自作のサーバに移行もありだと思いますが、他に意見があれば意見を貰えればと思います。

**Comment by dodoichi** [comment]
CloudのMQを使用する場合、クライアントのアドレスをサーバ側で知っておく必要があるかな？
あると面倒。

**Comment by disc99** [comment]
基本的にCloudでもサーバがクライアントを知る必要はないです！
user id、password、hostをクライアントが知っていれば、送信側も受信側もMQを使用出来ます。

ただ、MQに限らずですが、こういったprivateな情報をどう管理するか検討したほうが良さそうですね。
