### ISSUE TITLE
ロギングライブラリを選定する

### ISSUE THREAD

**Issue by ta-chibana** [javamas/araignee#17]
## 目的

Araigneeの実行結果を知るためのログを、どのライブラリを使って出力するか決める。
関連: #7 
## 選定基準

どのように選ぶべきなのかわからず、以下を基準に選定。
- よく使われているか
- できるだけ多くの情報が得られるライブラリであるか
## 選んだライブラリ

以下の理由から、SLF4J + Logback が良いのかなと考えました。
- Javaのロギングライブラリのデファクトスタンダード
- インターフェース（SLF4J）と実装（Logback）に分離
- ログのフォーマットや出力先、ログレベル等は設定ファイルで設定
- アダプタによって別の実装への移行が可能
## 参考

[Javaのログ出力: 道具と考え方](http://www.slideshare.net/miyakawataku/concepts-and-tools-of-logging-in-java)

**Comment by HomMarkHunt** [comment]
![LGTM](http://lgtm.in/p/uzK1wRzTp)

**Comment by HomMarkHunt** [comment]
> ログのフォーマットや出力先、ログレベル等は設定ファイルで設定

これは別チケット？

**Comment by ta-chibana** [comment]
> > ログのフォーマットや出力先、ログレベル等は設定ファイルで設定
> 
> これは別チケット？

別にしようと考えています！

**Comment by dodoichi** [comment]
[![LGTM](http://lgtm.in/p/axAWO2nfq)](http://lgtm.in/i/axAWO2nfq)

**Comment by ta-chibana** [comment]
可愛いのでclose!!
