### ISSUE TITLE
補助金の情報を取得するページを検討する

### ISSUE THREAD

**Issue by char-miki-tty** [javamas/araignee#19]
#4 の関連である

特に[新宿区のサイト](http://www.city.shinjuku.lg.jp/kodomo/file03_04_00006.html)が取得しやすい！！

**Comment by HomMarkHunt** [comment]
これは @char-miki-tty が決めてしまっていいような気がします。

**Comment by dodoichi** [comment]
児童扶養手当法により全国一律ならば、自治体のサイトを見る必然性は無いはず。自治体ごとに差異が出るなら意味があるけど。

**Comment by dodoichi** [comment]
ここで良いのでは？
http://www.mhlw.go.jp/bunya/shougaihoken/jidou/huyou.html

**Comment by char-miki-tty** [comment]
> 児童扶養手当法により全国一律ならば、自治体のサイトを見る必然性は無いはず。自治体ごとに差異が出るなら意味があるけど。

た、たしかに・・・！:bear:

> ここで良いのでは？
> http://www.mhlw.go.jp/bunya/shougaihoken/jidou/huyou.html

これだと特別児童扶養手当なので、障害を持つ子供限定になってしまいます。
そして、この厚生労働省の児童扶養手当のページを探したらPDFだったのです・・・。
http://www.mhlw.go.jp/bunya/kodomo/osirase/100526-1.html

**Comment by dodoichi** [comment]
ここは？
http://law.e-gov.go.jp/htmldata/S36/S36HO238.html

**Comment by char-miki-tty** [comment]
すみません・・・
読んでみたのですが、自分の頭では
( ᐛ ) パァ
でした。

**Comment by nayuta28** [comment]
http://law.e-gov.go.jp/htmldata/S36/S36HO238.html
ちゃんと読めてないのですが、

`第五条 　手当は、月を単位として支給するものとし、その額は、一月につき、四万千百円とする。`
`第五条の二 　前条第一項に規定する手当の額については、総務省において作成する年平均の全国消費者物価指数（以下「物価指数」という。）が平成五年（この項の規定による手当の額の改定の措置が講じられたときは、直近の当該措置が講じられた年の前年）の物価指数を超え、又は下るに至つた場合においては、その上昇し、又は低下した比率を基準として、その翌年の四月以降の当該手当の額を改定する。`
とあり、支給額は毎年改定されることは記載されていますが明確な金額や指数は載っていないようです。
支給金額の公表は厚生労働省の管轄でHP上にありましたが、PDFでした。
http://www.mhlw.go.jp/file/06-Seisakujouhou-12600000-Seisakutoukatsukan/teate.pdf

**Comment by dodoichi** [comment]
PDF読み込みにするか。。。

**Comment by char-miki-tty** [comment]
:bear: ﾄﾞｷｯ

**Comment by char-miki-tty** [comment]
新宿にします！！:bear:

**Comment by dodoichi** [comment]
![LGTM](http://lgtm.in/p/MOTaN42aq)
