### ISSUE TITLE
[要件] 何で助けるのか？

### ISSUE THREAD

**Issue by HomMarkHunt** [javamas/araignee#2]
# 何で助けるのか？
## 概要

何のデータを集めて育児に関わる人を助けるのか。
助成金・奨励金などのデータは様々あるが、具体的にどのデータを使うのか決定する。
## 担当

@ta-chibana @char-miki-tty @nayuta28

**Comment by nayuta28** [comment]
- 児童手当 (国の制度)
- 児童扶養手当（国の制度）
- 児童育成手当（ 区 (都) の制度 ）
- 特別児童扶養手当（国の制度）
- 就学援助費
- 私立幼稚園児の補助金 
- 認可外保育施設保育料助成制度 

母子・父子家庭や障害児の場合に支給される手当、子供の就学時など時期によって支給される手当もあるなど、どのデータを使うかは誰をターゲットにするかをまず絞ることによって決めたほうがいいのかな。

**Comment by HomMarkHunt** [comment]
確かに、#1 を先に決めないと**誰に何のデータを渡すのか**が決められないですね！

**Comment by dodoichi** [comment]
「何で」というのは、"Why"なのか"What"なのかわかりにくいね。

**Comment by HomMarkHunt** [comment]
あ、これは読みの問題で。
**「なにで」**ですので**What**ですかね。
Howっぽい感じもしてしまった。

**Comment by dodoichi** [comment]
広島市の児童扶養手当を参考にさせていただきましょう。
