### ISSUE TITLE
MQから#4が送信したデータを受信する

### ISSUE THREAD

**Issue by nayuta28** [javamas/araignee#21]
# 5の子チケット

**Comment by nayuta28** [comment]
ページの情報をどのように受け取るか
- htmlファイル
- String

**Comment by dodoichi** [comment]
進める前に、#13 を見てください。

**Comment by nayuta28** [comment]
#13のコンポーネント図にある通り、データの受け渡しはMQを介して行う。
MQからメッセージを受信する流れとして
1. ConnectionFactory生成
2. Connection接続
3. Consumerを宣言する
4. メッセージを受け取る
5. 受け取ったメッセージを処理する

**Comment by nayuta28** [comment]
- MQでよく使われるフォーマットを調査する
- 送信してもらうデータを決める

**Comment by ta-chibana** [comment]
> - MQでよく使われるフォーマットを調査する

#37

> - 送信してもらうデータを決める

#20
