### ISSUE TITLE
各ログレベルの基準を考える

### ISSUE THREAD

**Issue by ta-chibana** [javamas/araignee#23]
関連: #7 
## 検討事項
- ログレベルごとに利用する基準を決める
  - Logbackのログレベル
    - trace
    - debug
    - info
    - warn
    - error

**Comment by ta-chibana** [comment]
調べてみての考えとして、各ログレベルの用途は
- ERROR  
  システムが動作できなくなる様な致命的なエラーが発生した場合
- WARN  
  何らかの問題が発生したが、システムの動作は継続可能な場合
- INFO  
  何らかのイベントが開始、終了された場合
- DEBUG  
  動作状況の詳細な情報
- TRACE  
  DEBUGよりも詳細な情報

INFO以上についてはほぼ上記の扱いがされている様でした。
DEBUGとTRACEについては使い分けが曖昧な印象を受けましたが、
DEBUGはどのプログラム上のどの経路が実行されたかがわかるようなログを記録し、
TRACEは変数の参照情報といったDEBUGよりも細かい情報を記録する、といった記事も見受けられました。
ログレベルの基準はプロジェクトによりけりだとは思いますが、だいたいこういった分け方になるのでしょうか？

**Comment by dodoichi** [comment]
大体よいです。

> > > ERROR
> > > システムが動作できなくなる様な致命的なエラーが発生した場合

致命的なエラーが何を指すかが曖昧ですが、動作が停止する場合だけではなく、仕様に沿った処理ができない場合まで含めてください。

**Comment by ta-chibana** [comment]
ありがとうございます！

> 致命的なエラーが何を指すかが曖昧ですが、

致命的なエラーとは、「システムの動作が停止してしまうようなエラー」、という意味合いで書きました。

> 動作が停止する場合だけではなく、仕様に沿った処理ができない場合まで含めてください。

これも考慮すると、
- ERROR
  - システムが動作できなくなる様な致命的なエラーが発生した場合
  - 仕様に沿った処理ができない場合
- WARN
  -  何らかの問題が発生したが、システムの動作は継続可能な場合
- INFO  
  - 何らかのイベントが開始、終了された場合
- DEBUG  
  - 動作状況の詳細な情報
- TRACE  
  - DEBUGよりも詳細な情報

という感じになると思います！

**Comment by HomMarkHunt** [comment]
ゴールが見え無いのでなんともですが、ひとまずこれは終了で良いのでは？
また、log関係の取り決めはどこかにまとまってるとわかりいやすいなと思いました。(毎回このissue掘り起こすのも大変そう)

wikiかmarkdowns??

**Comment by dodoichi** [comment]
![LGTM](http://lgtm.in/p/YEJNVymOp)
