### ISSUE TITLE
ログローテーションの間隔について決める

### ISSUE THREAD

**Issue by ta-chibana** [javamas/araignee#25]
関連: #7 
## 検討事項
- 古いログファイルをどの程度の期間、保持しておくか決める

**Comment by dodoichi** [comment]
サイズ0 のログファイルが一杯あっても嫌なので、期間じゃなくてサイズでローテートするのもありかな。

**Comment by ta-chibana** [comment]
> 期間じゃなくてサイズでローテートするのもありかな。

今のところ頻繁に起動されることは考えにくいので、確かにサイズで良さそうですね。
ただ、どれくらいの量のログが記録されるかが把握できないので、設定で変更もできますし、どれくらいのサイズでローテートするかは後から決めても良いのかなと思いました！

**Comment by dodoichi** [comment]
仮で良いので、今、決めてください。

**Comment by ta-chibana** [comment]
はい！仮で決めてみます！

```
%d [%-5level] [%thread] %class{25}:%3line - %msg%n
```

#24 で決めた上記のフォーマットから考えて`%msg`に全角で30文字入ると考えても、
１行150Bで収まると思うので、仮に3MBあれば20000行ぐらいは記録できそう...
20000行あれば充分かなと思いましたので、**3MB**でどうでしょうか？

**Comment by dodoichi** [comment]
> 20000行あれば充分かなと思いました

何に対しての話でしょう？

**Comment by dodoichi** [comment]
このあたりのことを考えて欲しいです。
- 何世代保持する？
- 圧縮する？

**Comment by ta-chibana** [comment]
- ３世代
- 圧縮しない

**Comment by disc99** [comment]
[![LGTM](http://lgtm.in/p/ouHeH1Hcq)](http://lgtm.in/i/ouHeH1Hcq)

**Comment by dodoichi** [comment]
[![LGTM](http://lgtm.in/p/Q2w1WLwSp)]

**Comment by ta-chibana** [comment]
ありがとうございます！！
