### ISSUE TITLE
DBマイグレーションについて決める

### ISSUE THREAD

**Issue by HomMarkHunt** [javamas/araignee#26]
## 前提

DBを使用する際に下記理由からマイグレーションツールを使用する。
- 各環境(今の所想定は 各々のローカル と 本番環境)で容易にテーブル作成などを容易に行うために使用する。
- araingeeの要件としてテーブル構成が頻繁に変わることが想定されるので、DBのバージョン管理を行えるマイグレーションツールを使用する。
## 使用するツール
- [Flyway](https://flywaydb.org/)

<img src="https://cloud.githubusercontent.com/assets/14356345/15266130/4241372c-19d6-11e6-97ea-09716aff68b5.png" width="200" height="150">
### 選定理由
- 選考対象に **[Liquibase](http://www.liquibase.org/)**
- Liquibase のほうが高機能で複数のDBのサポートなどに強い(確信)
- 肝心の実行用のSQLが
  - Flyway : Plain SQL(標準DDL)
  - Liquibase : Liquibase XML, Liquibase annotated SQL(Plain SQLのサポート無し)

という違い。
- **Plain SQLを書きたい(Liquibase用のDB定義を覚えられる気がし無いみんなパニックになる)**
- Flywayも怪しいのでできるだけ低機能でシンプルに使えるFlywayのほうがいい
- 今回の使用用途として、DDLを流す、DBのバージョン管理くらいしか想定されてい無いので。Liquibaseの高機能はオーバースペック
- Java migrations (JDBC API を使ったJavaクラスのマイグレーション) がFlywayのみ

以上の理由からDBのマイグレーションツールは**Flywayを使用する**。
## Flywayの開発環境
- Flaywayが管理するパッケージ群をじゃばますOrganization配下に**専用のリポジトリを作成**して管理する。
- SQLの変更は当該リポジトリにてCommit
## Localでの使用方法
- 各PCに[Flyway Command-line Tool](https://flywaydb.org/getstarted/download.html)をインストール。
- Github上からFlyway用リポジトリをclone(二回目以降は最新をpull)し、当該ディレクトリにて `Flyway  Command`を実行。
- テーブルなど、最新のものが配備される。
## issue終了条件

@dodoichi @disc99 2名による`LGTM`を獲得。

**Comment by ftsan** [comment]
![寿司ゆき:ok](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/03.png)

**Comment by dodoichi** [comment]
![LGTM](http://lgtm.in/p/KnIv1P5Rp)

**Comment by disc99** [comment]
### 2点確認
1. Flyway Command-line Toolは本番環境でも使用する？
   となるとサーバにもToolをインストールする前提？gradlewやmvnwみたいな実行環境依存の無い仕組みで構築する前提じゃなくても大丈夫？
2. 別リポジトリで管理する場合、開発中のアプリリポジトリとFlywayリポジトリの整合性はどうやって維持する？
   場合によっては、ブランチ単位でテーブル構成が違ったりする状態は発生するはず。

**Comment by HomMarkHunt** [comment]
@disc99 

> 1. Flyway Command-line Toolは本番環境でも使用する？ となるとサーバにもToolをインストールする前提？gradlewやmvnwみたいな実行環境依存の無い仕組みで構築する前提じゃなくても大丈夫？

当初はサーバにもToolをインストールし、sshで手動で`flyway migtrate`とか叩く想定でしたが、手動での実行は事故りそうなのと某靴ECサイトの筋肉の人にアドバイスをもらい。
- migrate用のシェルを作る [参考](http://d.hatena.ne.jp/pospome/20150613/1434216556)
- ビルドツールから実行するようにする

のどちらかを考えています。

ビルドツールが決まっていないので今一歩決めかねている状況です。

> 1. 別リポジトリで管理する場合、開発中のアプリリポジトリとFlywayリポジトリの整合性はどうやって維持する？ 場合によっては、ブランチ単位でテーブル構成が違ったりする状態は発生するはず。

たとえばaraigneeのfeature/hogeで開発中にDBの変更があった場合はDB用リポジトリもfeature/hogeを作成して整合性を維持する想定です。

で、あればaraignee内でflawayも管理すれば... とも最初に思ったのですが。araigneeがデータ格納したDBを**使う側アプリ(名前未定)の作成中にDB構成を変えるケース**がほぼ確実にあるかなと考えています。

その時にDBの変更するためにaraignee自体を変更するのではなくDBだけは別で切り出したほうがわかりやすいかなと思ったのでこの構成を考えました。

回答が的を得ていなかったらすみません。

**Comment by disc99** [comment]
> たとえばaraigneeのfeature/hogeで開発中にDBの変更があった場合はDB用リポジトリもfeature/hogeを作成して整合性を維持する想定です。

運用方法が決まっているのであれば、別リポジトリでも大丈夫かな！
分離して管理するのが手間であれば、後で統合してもいいだろうし。

それと、Command-line Toolは使ったこと無いからよく分かってないけど、実行環境にインストール前提で開発を進めていくと後々環境の管理に苦しみそうだから、ビルドツールだけで完結できてたほうが、環境移行やローカルの環境構築も楽になると思う。

chappieがマイグレーションしてくれるってのも面白そうではあるけどｗ

**Comment by HomMarkHunt** [comment]
> ビルドツールだけで完結できてたほうが、環境移行やローカルの環境構築も楽になると思う。

ありがとうございます！ 
実行方法を調べてみたのですが、
1. command line tool(ターミナルからflywayコマンドで実行)
2. javaから実行(コード内からflywayを実行)
3. Gradleのpluginとして実行

という方法があるみたいです。
ローカルは1. 本番は3.の実行方法がいいかなと思いました。

一度手元で諸々試してみます！

**Comment by disc99** [comment]
ローカルを1にしたい理由はある？
それだと環境によってコマンドを使い分けないといけないのと、command line toolのバージョンコントロールが出来ないから、ローカルも本番も全部Gradleで実行するようにしてしまったほうが楽な気もするけど！

**Comment by HomMarkHunt** [comment]
> ローカルを1にしたい理由はある？

あー。これは以前現場でflyway使ってた時にローカルはコマンド叩いてたから。ってだけですね！確かに両方Gradleから実行のほうが良さそうです！

**Comment by disc99** [comment]
[![LGTM](http://lgtm.in/p/MAYAN1xCn)](http://lgtm.in/i/MAYAN1xCn)

**Comment by HomMarkHunt** [comment]
まとめ書いてて出てきた確認したいことがでてきました。

### migrateするgradleタスクはどこに記述するか
- araignee内のビルドスクリプト
- DB管理リポジトリのビルドスクリプト

のどちらにgradleタスクを書くべきか？
当初ふわっと考えていたのが _「DB管理リポジトリをgradleで作成して `build.gradle` 内にmigrate用の諸々を記述」_ です。
その場合、
1. サーバーにDB管理用のプロジェクトを配置(デプロイ？)
1. migrate時はサーバーにアクセスしてmigrate用のタスクを実行

もしくは、
1. araignee内のビルドスクリプトにmigrate用のあれこれを記述してデプロイ後にタスク実行できるようにする

のどちらかの方法で実行できるようにする必要があると思いました。

この認識であっていますでしょうか？

**Comment by dodoichi** [comment]
こういうことを悩むくらいなら、レポジトリを分けない方が良いだろうね。

**Comment by HomMarkHunt** [comment]
むむむ...
確かによくわかってないですぞ...

Gradleから実行されるFlywayが**どこのSQL**を**いつ実行するのか**がよくわかっていないなと思いました。
まとめ書いてて、仰る通り「araigneeに書いたほうがまだわかるのでは...」と思っていました。

今回はaraigneeの `build.gradle` に記述して、SQLもaraignee内に含める。に返させていただこうと思います。

お二人せっかく見ていただいたのに申し訳ございません。一旦まとめ直します。

また、今度お時間あるときにちょっと質問させていただけると嬉しいです。

**Comment by dodoichi** [comment]
[![LGTM](http://lgtm.in/p/KBtEvxT2q)]

**Comment by HomMarkHunt** [comment]
このチケットで決めるべきこと。(flywayを使う)は決まり、終了条件であるLGTM2つも獲得済みなので、本チケットはクローズし。
Flywayをどのように利用していくかは #39 にて決めます。よってクローーーズ！！
