### ISSUE TITLE
Issue、Pull Requestのテンプレートを登録する

### ISSUE THREAD

**Issue by dodoichi** [javamas/araignee#27]
## 背景

[Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates)を見て、 javamas/stunning-eureka で試したので、テンプレートを導入しようと思います。
## 関連するIssues

javamas/stunning-eureka#1, javamas/stunning-eureka#2

**Comment by HomMarkHunt** [comment]
[![LGTM](http://lgtm.in/p/42I5Qj6hq)](http://lgtm.in/i/42I5Qj6hq)

[:+1:](http://lgtm.in/u/42I5Qj6hq) [:-1:](http://lgtm.in/r/42I5Qj6hq)

**Comment by HomMarkHunt** [comment]
このtemplateに修正や追加依頼を出したいときは[stunning-eureka](https://github.com/javamas/stunning-eureka)にプルリクを送るのがいいですかね？

**Comment by dodoichi** [comment]
そうですね、固めておいた方が経緯を追いやすいので、それがよいでしょう。
