### ISSUE TITLE
[導入] いつどんなときに使って欲しいのか？

### ISSUE THREAD

**Issue by HomMarkHunt** [javamas/araignee#3]
# いつどんなときに使って欲しいのか？
## 概要

育児を助けるとしたが、どういったタイミングに使って欲しいのか。
使って欲しいシチュエーションを考える。
## 担当

@HomMarkHunt @nayuta28 @char-miki-tty

**Comment by ta-chibana** [comment]
手当が欲しいと思うタイミングは「お金が必要だ！」と感じるとき？
- [生活費が心配](http://single-mama.hatenablog.com/entry/2014/07/28/230818)
- [進級・進学](http://www.travelearth.info/%E4%BD%93%E9%A8%93%E8%AB%87/%E6%AF%8D%E5%AD%90%E5%AE%B6%E5%BA%AD%E3%81%A0%E3%81%A3%E3%81%9F%E3%81%AE%E3%81%A7%E3%80%81%E5%A5%A8%E5%AD%A6%E9%87%91%E3%82%92%E5%80%9F%E3%82%8A%E3%81%A6%E5%A4%A7%E5%AD%A6%E3%81%AB%E8%A1%8C%E3%81%8D/)
- [転居](http://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q1441532094)

市営住宅というワードもちらほら見えました。

**Comment by nayuta28** [comment]
子供のいる友人などに話を聞いてみたところ、手当や助成について考えたり調べたのは結婚後（家族計画的なことを話すときとか）・妊娠期が多いそう。
出産後は育児で手一杯になってしまうそうだからそうした準備期間にデータを集めたり考えの補助的に利用してもらえるといいのかな。

**Comment by nayuta28** [comment]
ここじゃなくて少し#1 よりな意見だったかも

**Comment by char-miki-tty** [comment]
自分が妊娠してる気持ちで考えてみたら（笑）産まれる前に色々調べそうな気がする！
今一番問題になってるのは保育園かな？保育園に決まらないと仕事復帰できないし。
お金さえあればいくらでも入れる所あるらしいけど。。。
一番最初にぶつかる壁だって友達が言ってたよ！

**Comment by HomMarkHunt** [comment]
生まれる前ってのもありそうですね！
より助けたいシーンを考えたら、(理由は様々ですが)旦那さんが突然いなくなってしまって子供と母だけになってしまった時など助けたいなと思いました！

**Comment by dodoichi** [comment]
所得が少なく、育児に余裕が無いときから開始。
