### ISSUE TITLE
buildに使用するツールを決める

### ISSUE THREAD

**Issue by dodoichi** [javamas/araignee#32]
## Context

ビルドに使用するツールが決まらないと、困っているメンバーがいる。
## Problem, Idea

ビルドツールが決まってない。
## Solution, next step

 gradleを使う。
## Issue links
#26

**Comment by dodoichi** [comment]
@javamas/javamas-admins 
[Gradle](http://gradle.org/)でいきましょう。

**Comment by HomMarkHunt** [comment]
![LGTM](http://lgtm.in/p/oEkAbqQ3q)

**Comment by ta-chibana** [comment]
![LGTM](http://lgtm.in/p/WxkOXAtVp)

**Comment by disc99** [comment]
[![LGTM](http://lgtm.in/p/sshifZM6q)](http://lgtm.in/i/sshifZM6q)

**Comment by disc99** [comment]
Kotlin Gradleって選択肢もありますがｗ
http://gradle.org/blog/kotlin-meets-gradle/

**Comment by HomMarkHunt** [comment]
> Kotlin Gradle

まだ、Jet Brains製品のみのサポートみたいですね
EclipseはCooming Soonらしい。

https://youtu.be/4gmanjWNZ8E

**Comment by disc99** [comment]
EclipseはそもそもGradleもGroovyもサポートとか機能面とかだいぶ出遅れてるからねー
Kotlinも面白そうではあるけど、今使うならGroovyだろうね！

**Comment by dodoichi** [comment]
[Wiki](https://github.com/javamas/araignee/wiki/Environment)にも記載したので、closeします。
