### ISSUE TITLE
起動クラスを用意する

### ISSUE THREAD

**Issue by ta-chibana** [javamas/araignee#36]
## Context

Araigneeは、Collector, Transformer, Loaderと分かれていて、このIssueはCollectorに起動クラスを扱う。後の2つは常時起動になる。
## Problem, Idea

起動クラスがないと、Collectorが動かない。
最終的に正常終了したかどうか、判定できると(ﾟдﾟ)ｳﾏｰ。
### Input

引数

| キー | 値 | 制約 |
| --- | --- | --- |
| args[0] | サイトURL | 必須 |

VM引数

| キー | 値 | 制約 |
| --- | --- | --- |
| mq.host | host | 必須 |
| mq.user | MQ接続ユーザ | 必須 |
| mq.password | MQ接続パスワード | 必須 |
| mq.vhost | virtual host | 必須 |

(*) キーは仮置き、後で確認する。
### フロー
1. 引数、JVM引数を受け取る
2. 入力値の検証
3. Collectorの呼び出し
4. 結果取得の待受
## Issue links
#22 起動時(、終了時)のログは通知される。

**Comment by dodoichi** [comment]
起動クラスは不要になった為、Close。
