### ISSUE TITLE
MQでよく使われるフォーマットを調査する

### ISSUE THREAD

**Issue by nayuta28** [javamas/araignee#37]
## Context

MQでよく使われているフォーマットを調査し、今回利用するデータ形式を決定する

**Comment by nayuta28** [comment]
MQでのデータフォーマットについて調査を行いましたが、あまり情報が多くなくその中ではjsonが多い印象でした。

jsonを採用した場合
- JacksonやGsonなどのjsonパースライブラリを使わなければならない（使わなくても出来る方法もあるようだったがコードが複雑だった）
- 外部システムとの連携があるわけではなく、アレニエ内のデータ受け渡しに利用するためデータ形式にこだわり過ぎなくてもいい・・・？

上記からjsonは採用せず、送受信するデータオブジェクトをバイナリデータに書き換え送信する、受信したバイナリデータをデータオブジェクトに変換する方法を採用したいと思っています。

送信部分抜粋

```
    SampleMessageObject sample = new SampleMessageObject("Hello World", 28);
    ByteArrayOutputStream baos = new ByteArrayOutputStream();
    ObjectOutputStream oos = new ObjectOutputStream(baos);
    oos.writeObject(sample);
    channel.basicPublish("", QUEUE_NAME, null, baos.toByteArray());
```

受信部分抜粋

```
    public void handleDelivery(String consumerTag, Envelope envelope, BasicProperties properties, byte[] body) throws IOException {
    ByteArrayInputStream bais = new ByteArrayInputStream(body);
    ObjectInputStream ois = new ObjectInputStream(bais);
    SampleMessageObject sample = (SampleMessageObject) ois.readObject();
```

**Comment by disc99** [comment]
chappieからCollectorへのメッセージ送信はどうする？
単純な文字列？

**Comment by nayuta28** [comment]
あ。。
すみません、そうですねchappie→Collectorのところ抜けてました。。
chappieから文字列を送ってもらうことって出来るんでしょうか？
MQ処理を共通化するのであればフォーマットも統一してしまいたいと考えているのでここがjsonになるのであれば、上のコメントと180度変わってしまいますがjsonにしようと思います。

**Comment by disc99** [comment]
MQ上は、jsonでもxmlでも結局文字列だから形式さえ決まってればやり取りは問題ないよ！
今回要件だと、確かにjsonが一番上扱いやすいと思う！

**Comment by nayuta28** [comment]
ありがとうございます！
それではMQ共通処理で使用するデータ形式はjsonを採用する方向で行きたいと思います！

**Comment by disc99** [comment]
[![LGTM](http://lgtm.in/p/sKGC3urSp)](http://lgtm.in/i/sKGC3urSp)

**Comment by dodoichi** [comment]
共通処理でjson使うと、loaderは受け取ったオブジェクトをそのままDBに保存できなくなるね。一度jsonを読み込んで、永続化するインスタンスを生成することになる。@honmarkhunt のやる事が増えるね。jsonやxmlで受け渡すなら、モデルの定義を待つ必要はないな。

**Comment by disc99** [comment]
> 共通処理でjson使うと、loaderは受け取ったオブジェクトをそのままDBに保存できなくなるね

そうですね、ここも前回最初に少し話しをしていたのですが、共通処理部分をどこまで抽象化するかによってくるかと思っています！

channelの生成部分のみを抽象化するのであれば、使う側が通信形式を意識する必要があると思います！
逆に共通処理へはJavaオブジェクトの受け渡しのみで、共通処理内でjsonへの変換+MQとの処理を行うのであれば、そこの形式は共通処理内だけで完結出来るのではないかと思っています！

**Comment by dodoichi** [comment]
JSONをパースする部分まで閉じ込めるのであれば、あとで丸々取り替えることもできるので、やってもいいか

![LGTM](http://lgtm.in/p/EkaYsnRRp)

**Comment by nayuta28** [comment]
うわーー！
すみませんありがとうございます・・・！！

> 共通処理へはJavaオブジェクトの受け渡しのみで、共通処理内でjsonへの変換+MQとの処理を行うのであれば、そこの形式は共通処理内だけで完結出来るのではないかと思っています！

この方針で進めます！
本当にありがとうございます！！

方針が決まりましたのでこのissueはcloseさせて頂きます。
