### ISSUE TITLE
Flywayの運用方法について決める

### ISSUE THREAD

**Issue by ta-chibana** [javamas/araignee#38]
## Context

DBのマイグレーションツールとしてFlywayを使用することは決まったので、
- ローカル
- 本番
- ~~(ステージングとかないよね..??)~~

でどういった手順で運用するか決める。
### 導入
- ビルドスクリプト(`build.gradle`)にpluginとしてflywayをinstall
- SQLファイルのファイル名と配置は[Flywayのデフォルト](https://flywaydb.org/documentation/migration/sql.html)通りにaraignee内にする
### 実行

ローカル、本番共にFlywayの実行方法
- flyway command line tools
- gradleのタスクで実行
- Javaで実行

の中から、**gradleのタスクで実行**する。
### ローカルでmigration
- DB定義に変更があった場合、各位が`gradle flywayMigrate`を実行する。
### 本番環境でmigration
- ~~**ここがわからない、以下コメントで考察**~~
- ビルドtoデプロイの間で `gradle flywayMigrate` が実行するようにする。
## Solution, next step

例によって dodoichi disc99 2名によるLGTM獲得でclose
## Issue links
#26

**Comment by HomMarkHunt** [comment]
## 本番環境でのmigrateについて

ここがよくわかっておらず、本チケットを進める事が出来ません..
今思ってるイメージを書きますので、ご査収願います。

## 想定している手順

前提：**本番環境へのデプロイはCIから行う。**
1. migrationファイルを作成(編集)したら(レビュー後)masterブランチにマージ
2. CIがビルドしてデプロイ(手動？自動？)
3. ビルドのタイミングでgradleのタスクでmigrationが走る
4. やった！本番DBのmigration成功！

**Comment by dodoichi** [comment]
build と deploy の間で、`gradle flywayMigrate` が実行されるように設定すればよいかと思います。

![LGTM](http://lgtm.in/p/MwCQCbseq)

**Comment by disc99** [comment]
[![LGTM](http://lgtm.in/p/cSsBwGJbq)](http://lgtm.in/i/cSsBwGJbq)

**Comment by HomMarkHunt** [comment]
わーい！
ありがとうございます！

ビルド -> デプロイ間に正直どうやってタスクを作っていいかはイメージできていないのですが。
- 本チケットで決めることは決まった。
- CIツールが決まらないと調査できない。

ので本チケットは一旦クローズして、忘れないために新しく「本番でのマイグレートを決める」的なチケットを作ってBackLogに置いておこうと思うです！

というわけでクローズ！
- 一旦本チケットはクローズ
-
