### ISSUE TITLE
サーバーマシンに名前をつける

### ISSUE THREAD

**Issue by char-miki-tty** [javamas/araignee#40]
## Context

PCは組み上がった。
きっとこれから大活躍するだろう。
しかし、大きな問題が発生した。

そう。名前がないのである。

「サーバー」「作ったやつ」など不明確な名前で呼ばれることが想定される！
なのでみんなで名前をつけよう！！！
## Problem, Idea

**ルール**
1. 思いついたらコメント欄に指定フォーマットで記載(フォーマットは別途記載)。
2. 投稿は何度行っても良いが、あまりに多重投稿するとうざい。考え抜いたやつで。
3. 良いと思った名前には、各位 👍 をつける。
4. 👍 は1投稿1票。同じ投稿に同一人物が複数回の 👍 は禁止。
5. 自分の投稿への 👍 禁止。
6. 投票期間は1週間、**5/30(mon) 00:00 ~ 6/5(sun) 23:59**
7. 締め切り時に 👍 の数が同率だった場合なんか考えます。
## Solution, next step

サーバーの名前が決まったらクローズ。

**Comment by HomMarkHunt** [comment]
## 名前投票フォーマット

以下をコピペして投稿してください。
↓↓↓↓↓↓↓↓↓↓

<p>### 名前</p>

名前(読み)

<p>### 由来</p>

由来やなぜその名前にしようかと思ったかの動機など

<p>### ポイント</p>

<p>* ポイント1</p>

<p>* ポイント2</p>

<p>* ポイント3</p>

## サンプル

### 名前

バジオウ(ばじおう)

### 由来

漫画、キングダムのキャラクターから。
強キャラなのでサーバーの名前にいいかと思った。

### ポイント
- 呼びやすい。呼び心地がいい。
- 「バジオウ ニ デプロイ」という響きがかっこいい。
- 工場出荷時に戻すときに、「昔のバジオウに戻す」と、言う言い方ができる。

**Comment by char-miki-tty** [comment]
> 工場出荷時に戻すときに、「昔のバジオウに戻す」と、言う言い方ができる。

バジオウいいなぁ:bear:

**Comment by dodoichi** [comment]
### 名前

CBS-70 PUTOLEMAIOS(トレミー)

### 由来

機動戦士ガンダム00から。
マシンはあくまで入れ物なので、中に載るもののことも考えないと。

### ポイント
- 自然にGuestの名前が決まる。こんなに載らないが。
  1. EXIA(エクシア)
  2. DYNAMES(デュナメス)
  3. KYRIOS(キュリオス)
  4. VIRTUE(ヴァーチェ) -> NADLEEH(ナドレ)
- 副作用として、武力で戦争をなくす覚悟が芽生えるかもしれない。
- [こんなの](https://www.ark-pc.co.jp/i/24300803/)をつけると、「トランザム」って言えるぞ。

**Comment by disc99** [comment]
### 名前

JWS(じぇーだぶりゅえす)
Javamas Web Services

### 由来

類似サービス ○mazon Web Servicesより

### ポイント
- なんか高機能そう
- なんか拡張性高そう
- ガチでAWSに移行することになると、名前がややこしそう

**Comment by char-miki-tty** [comment]
### 名前

黒透(くろすけ)

### 由来

黒いし、透けてるし

### ポイント
- 黒い
- 透けてる
- 愛着が湧く名前だなぁ

**Comment by HomMarkHunt** [comment]
@javamas/javamas-admins 
同率なので投票お待ちしています！

**Comment by HomMarkHunt** [comment]
黒透で決定！
