### ISSUE TITLE
グラボの購入

### ISSUE THREAD

**Issue by char-miki-tty** [javamas/araignee#41]
## Context
#11 の選定でマザボにオンボードのグラボがなかったので、購入して後付けする。
## Problem, Idea
- ゲームしない
- むしろCUI画面しか見ない

ので取り付け可能な最安のもので良い。
## Solution, next step

届いたら取り付け！ #45 
## Issue links
#11 #45

**Comment by HomMarkHunt** [comment]
これが一番最初に取り組むやつですかね。
チケットたくさん出来ましたが @char-miki-tty に押し付けずみんなで考えてできるとこやってきましょう！じゃないと終わらん！

まず、グラボは一番安いやつで良いと思うので、
- http://www.amazon.co.jp/gp/aw/d/B00WHYPXDQ/ref=pd_aw_sim_147_1?ie=UTF8&dpID=41KUEnNhpzL&dpSrc=sims&preST=_AC_UL100_SR100%2C77_&refRID=1FGQN2RXKCP9YKT081R3

これでどうでしょう！

また、PCの保存場所についてですが。
あそこにはいつまでも置いておけません。出来れば明日月曜、ぎり今週いっぱい、最悪次の開放デーと言われてます。置かせてくれたあの人へ迷惑になるので即刻撤収が目標です。

撤収目標は #43 #44 の完了かな？

**Comment by ta-chibana** [comment]
> 撤収目標は #43 #44 の完了かな？

ゲストOSのインストールの前に#42 も必要ですね。

**Comment by HomMarkHunt** [comment]
OSのインストールが終わったら持って帰るという意味です。

**Comment by HomMarkHunt** [comment]
到着しました！！特にレビューしていただくことはないのかな？と思いますので、HonMarkHuntが自分でクローズします！！
<img src='https://cloud.githubusercontent.com/assets/14356345/15634271/afacdcbe-25fa-11e6-9786-337c95fd530b.png' width='300' height='450'/>

**Comment by ta-chibana** [comment]
もうcloseされちゃいましたが

![LGTM](http://lgtm.in/p/4qAXOcF8q)
