### ISSUE TITLE
グラボの取り付け

### ISSUE THREAD

**Issue by char-miki-tty** [javamas/araignee#45]
## Context

購入したグラボを取り付ける。
## Problem, Idea

5/30(mon) 19時頃いつもの場所で取り付け！
## Solution, next step

無事Biosの画面が表示されたら終了！
## Issue links
#41

**Comment by HomMarkHunt** [comment]
http://www.pc-master.jp/jisaku/graphicsboard-k.html

これを参考にしたら簡単にできそう。

**Comment by HomMarkHunt** [comment]
取り付けて無事に画面表示されました！

**Comment by disc99** [comment]
[![LGTM](http://lgtm.in/p/WRuksC2dq)](http://lgtm.in/i/WRuksC2dq)

**Comment by dodoichi** [comment]
![LGTM](http://lgtm.in/p/sctYtih5q)
