### ISSUE TITLE
ZenHubのInReviewに移動していい条件を考える

### ISSUE THREAD

**Issue by HomMarkHunt** [javamas/araignee#46]
## Context

じゃばます！全体のIssueの消化具合が芳しくないので(一番は私、ほんとうにごめんなさい)
ZenHubのPipelineの `InReview` に移動して良い条件を精査したい。
#### レビュイー
1. 各担当ごとにIssueを切り : `InProgress` , `BackLog`
2. 手をつけたら : `InProgress`
3. 終わったら : `InReview`

という流れでZenHubを使用しているが([wiki](https://github.com/javamas/araignee/wiki/About-ZenHub)より)、
Issue毎に**疑問・難しい事・うまく質問できない事...** にぶち当たった時に作業が進まず、全体的な進みが悪いような気がしています。(主に私)
顔を合わせた時に、
- 「そういえばあのチケットって...」
- 「◯◯さんのチケットのあそこって...」

などの会話がよく出るのは上記理由が原因かな？と感じます。
#### レビュワー

疑問点はIssueのコメントにメンションをつけてだったりSlackで質問したりさせて頂いていますが。
- メンションを見失うとチケットを探すのが困難だったり
- どこから質問が来てるのかわかりづらかったり

するのかと思います。
### Idea

`InReview` に **達成していないけど解決の妨げになる悩んでいる事** を書いて移動しても良い。

と、いうルールがあると。
- レビュワーのブロッカー解決がしやすくなる
- レビュイーは常に `InReview` を確認するだけで良くなる

という効果が得られるのかなと思いました。

決め事として
- なんでもかんでも `InReview` に移動しては、レビュワーが大変。しっかりとブロッカーを明記して質問する。(とはいえ理解ができず全く手がつけられ無いやつは、調査した範囲を報告してしっかりその旨を伝える)
- `InReview` にレビュー待ちと質問が混在するとレビュワーが大変なので、質問のIssueはタイトルの先頭に `WIP:` をつける。

と、いうのを考えました。

皆さん、いかがでしょうか？
(元からそういう想定でしたら申し訳ございません。)
## Solution, next step

全員のLGTMで採用とみなしクローズ。
不採用でもクローズ。
採用された場合は @HonMarkHunt がwikiに追記。
## Issue links
#9 #14

**Comment by disc99** [comment]
確かに、分かれて開発するときこの問題はよく引っかかるところだね！

ここでやらないければならないのは、今抱えている問題を出来るだけ早期に解決することだよね？
個人的には、InReviewもいいけど、SlackにQA用のChannelとか作って、チャット上で話し合ったほうが早く解決するんじゃないかと思っている！

Issueは分類されてて分かりやすいし、一問一答みたいに答えれるものにはいいんだけど、ディスカッションはちょっとしにくい気がする。
気軽にも聞きにくいしねｗ

イメージ的には、
1. Issueに対して悩みを抱える
2. SlackのQA Channelに助けを求める
3. 話し合って悩みをスッキリさせる
4. 話し合いの重要なところを抜粋してIssueに記載する

という感じ！

**Comment by dodoichi** [comment]
そだね〜。🐼に賛成。

**Comment by HomMarkHunt** [comment]
@disc99 @dodoichi 

ありがとうございます！

> 今抱えている問題を出来るだけ早期に解決することだよね？

そうです！

仰る通りチャットが一番議論進めやすいなと思いました！
逆にissue上でチャットのようになってることもある( :panda_face: 「チャットで良くない？」と、仰ってましたね。)ので、明確に質問用の部屋があるのはいいな~と思いました！！！！

@nayuta28 @char-miki-tty @ta-chibana もLooks good to meであれば、SlackにQA部屋作って本issueはクロージャーします。
何か意見があれば教えてください！

**Comment by ta-chibana** [comment]
![LGTM](http://lgtm.in/p/cgfWfFNnq)

**Comment by nayuta28** [comment]
![LGTM](http://lgtm.in/p/oyl2NiELn)

**Comment by char-miki-tty** [comment]
[![LGTM](http://lgtm.in/p/OFSshQ75q)](http://lgtm.in/i/OFSshQ75q)

**Comment by HomMarkHunt** [comment]
**SlackにQA部屋を作る** で決まったのでクローズします！
