### ISSUE TITLE
Araigneeのテストについて考える

### ISSUE THREAD

**Issue by dodoichi** [javamas/araignee#47]
## Context

そろそろ実装に入る予定だが、どのようにテストを進めるか決まっていない。
## Problem, Idea

このままだと、なんとなくテストコードを書いて満足しそう。
## Solution, next step
- 実施するテストの種類を決める
- テストを管理するツールを決める
- テスト実施のタイミングを決める
- 手動、自動などのテストの実施方法を決める

**Comment by dodoichi** [comment]
## 方針

まずは、動作することが確認する。その上で余裕があれば性能も気にかける。

## 種類

### 必須

### 静的解析

CheckStyle、FindBugsなどの解析ツールで、不具合の発生を抑える。
CIでも実行する。

#### Unitテスト

JUnitのテストコードを実装し、CIでも実行する。
プログラムの不具合を発見する。

#### 機能テスト

手動でも自動でもよい。無理は禁物。
要件に沿った動作をすることを検証する。

### できれば

#### 性能テスト
- パフォーマンステスト
- 負荷テスト

**Comment by dodoichi** [comment]
機能テストのやり方を考えないと。
テストケースを残しておかないと、回帰テストができなくなる。
どこに保存するか？

**Comment by dodoichi** [comment]
あまり大げさにせず、Issueに書けばよいか。
- ラベル(functional test かな)をつける
- ケースは表にする
- 事前条件を書く
- 実施は別Issue

**Comment by dodoichi** [comment]
@javamas/javamas-admins

**Comment by disc99** [comment]
[![LGTM](http://lgtm.in/p/YURtD2qXp)](http://lgtm.in/i/YURtD2qXp)

**Comment by HomMarkHunt** [comment]
@dodoichi 
ありがとうございます！
一点だけご確認させていただきたいのですが、

> 事前条件を書く

機能テストの事前条件に、**特定のDBのデータがある前提** のテストがあった場合。
機能テスト用のSQLはどこに保存するのが良いですかね？

機能テストの項目がはっきりと見えておらず、DBのデータなぞ必要無い！！という前提でしたら申し訳ございません。

**Comment by dodoichi** [comment]
ケースとセットになってないと回帰テストができないので、Issueに添付しておくのがいいかな。

**Comment by HomMarkHunt** [comment]
オウケイで〜〜す！！

![LGTM](http://lgtm.in/p/g21zr0N7q)

**Comment by dodoichi** [comment]
みんな見てないけど、もう閉じちゃいます。
