### ISSUE TITLE
MQへの送受信を共通化する方法を検討する

### ISSUE THREAD

**Issue by nayuta28** [javamas/araignee#48]
## Context

各機能でConnection接続などの処理を書くのは冗長になるから、共通化をする
### MQへの送信受信するクラスを共通化するか？
- 共通化する
### 前提
- Channnelオブジェクトを返すクラスを作る
- コネクションの取得などを毎回書くのは面倒だから
- https://www.rabbitmq.com/tutorials/tutorial-one-java.html
### どこまで共通化するか
- 接続
- メーセジのフォーマットに沿って変換する
- 送受信
### どのように共通化するか
- Contrller, Transfer, Loaderのクラス内で高塩作成のMQTemplete(仮)を使用する

**Comment by nayuta28** [comment]
@javamas/javamas-admins

**Comment by dodoichi** [comment]
![LGTM](http://lgtm.in/p/Y4fbBmbnq)

とにかく、一度実装してみようよ！

**Comment by nayuta28** [comment]
MQ共通クラスでは、
- 接続
- Channelオブジェクトの生成
- jsonへの変換(#37 で決定)
- メッセージの送受信

を行う方針で行きます！
@disc99 さんの 👍 をLGTMだと思うことにしてこのissueをcloseします！
