### ISSUE TITLE
システムが、運用者のコストを抑えるために、設定をもとに自動でバッチを実行できる

### ISSUE THREAD

**Issue by dodoichi** [javamas/araignee#8]

**Comment by disc99** [comment]
### 相談

打ち合わせの感じからいくと、Webからバッチを実行できる形がよさそうでしたが、となるとWebからのインターフェイスが必要になります。
ということで、それに対してどうするか候補をあげるのでみなさんの意見をもらえればと思います。
1. Webから使わない
   - 動作イメージ: cron -> [command] -> araignee起動
   - やること: cronの使い方ページをwikiに貼る
2. Web向けのアプリを別に作り、そこからバッチを起動する
   - 動作イメージ: Slackとか -> [http request] -> new Webアプリ -> [command] -> araignee起動
   - やること: Webから実行できるアプリを作る、外部から呼びさせるサーバとかをいろいろ
3. MQを使う
   - 動作イメージ: Slackとか -> [message] -> MQサーバ-> [message] -> araignee(常駐)
   - やること: きっといろいろ(TODO:やるならちゃんと調べる)

個人的には使ったことがないのと、いろいろ汎用性もありそうなので3がいいのではと思っていますが、みなさんの意見や他に候補があれば教えて下さい！

**Comment by dodoichi** [comment]
他に候補を挙げるなら、
- OSS使う
  ex. Rundeck

後々のことを考えると、
1. 自律プログラムがサイトを巡回
1. 更新を発見
1. イベントをキューに追加
1. キューの追加を検知してバッチ起動

とか、
1. サイトの更新をHTTPリクエストで通知
1. リクエストをWebシステムが受信
1. キューに（以下同文）

とかあるかもしれないので、
3番が面白そうかな。

**Comment by disc99** [comment]
ありがとうございます！
私も同じような想定をしていました。

Rundeckも初め少し考えたのですが、Webから使えるcron + αみたいなイメージだったので、外からバッチを起動させる目的だとちょっと持て余すかと思っていました。
他にもOSSは探せばいろいろありそうですが、そしたら一旦3で進めます！

もしも他に意見があれば教えて下さい！

**Comment by char-miki-tty** [comment]
動作イメージはあまり出来ていなかったのですが、自分は何となく2の方法なのかなと思ってました。

3のMQを知りませんでした。。。すみません。。。
提供元のサイトが更新された場合、自動で更新が通知される機能を実装できるのがMQになるんですか？

**Comment by disc99** [comment]
MQに関しては文章だけだと説明が難しいので、次回のMTGの時までに情報をまとめとくね！

基本的には
1. MQを実現するミドルウェア(具体的にはRabbitMQとかMosquittoなど)をインストールしたサーバを用意する
2. バッチ側はMQに決められた形式のメッセージが届くのを監視する
3. バッチを動かしたい人は、MQにバッチが監視している形式メッセージを送信する
4. 監視しているバッチがメッセージを受け取り処理を開始！
みたいな動きになる想定です 🐼 

今回の場合、MQ自体はあまりやることは無くて、届いたメッセージを順次配信する役目みたいな感じかな！

**Comment by char-miki-tty** [comment]
うおぉぉーーー！ありがとうございます！！
次回のMTGまでに自分でももう少し調べて整理しておきます！

**Comment by ta-chibana** [comment]
説明終了したのでclose!!
