### ISSUE TITLE
管理計画

### ISSUE THREAD

**Issue by dodoichi** [javamas/araignee#9]
# 計画
## コード

当然、GitHubで管理する。
ワークフローは、
1. ~~git-flow~~
   https://www.atlassian.com/ja/git/workflows#!workflow-gitflow
   - よく使用される
   - 厳格
2. github-flow
   https://guides.github.com/introduction/flow/
   - シンプル

~~あたりが候補。~~
## ドキュメント

Wikiに書きためていきましょう。

カチッとしたものを書くことより、思ったことをひたすら書きなぐるスタイルの方が、議論も活発になりそう。
#12 Wikiについてはこちら。
### Issues

ZenHubを使用し、Boardで運用する。
- 全体のざっくりした構成を決める
  - Epicで細かいIssueをまとめる
  - Issueのテンプレートを用意
  - ガイドラインを用意
- Wikiのガイドラインが必要なら制定する
  - あまり細かいことは気にしない
## MTG

集まって話し合うことと、Slackで済ませることを意識して、実のあるMTGにしていきましょう。
- 16/05/11 要件レビュー
### 予定の共有
- Google Calendarに予定を登録
  - Calendarに招待
- Slackで予定を通知
  - 号外
## 調達
- マシン調達 #10 
- サーバ構築 #28
- ドメイン取得 #29
## スケジュール

リリース日は仮置き。リリースから逆算でざっくりスケジュールを決める。

ここに示したものは、「完了予定日にここまでは決まってないと厳しい」という目安です。
実際は、設計/実装/テストを並行で進めながら、フィードバックを元に行ったり来たりすると思っていてください。
- Atypus karschi (地蜘蛛)
  - 要件定義 ~ 16/05/13
  - マシン調達 ~ 16/05/28
  - 設計 16/05/14 ~ 16/05/20
  - 実装準備 16/05/21 ~ 16/05/27
  - 実装/UT 16/05/28 ~ 16/06/10
  - サーバ構築 16/05/29 ~ 16/06/11
  - IT/ST 16/06/11 ~ 16/06/17
  - リリース準備 16/06/18 ~ 16/06/24
  - リリース 16/06/25

**Comment by dodoichi** [comment]
document は、Wiki にあげる。
どんなものがあるだろう？

**Comment by dodoichi** [comment]
MTGは今のところ2週に1回。
内容はレビューがメインか？

**Comment by dodoichi** [comment]
サーバの調達が必要。
自作…か！？

**Comment by dodoichi** [comment]
コードは当然GitHubで管理。
運用はGit Flowで大丈夫？

**Comment by dodoichi** [comment]
スケジュールは6末初回リリース。
WBS欲しいかな。

**Comment by char-miki-tty** [comment]
はい！私サーバーやりたいです！

**Comment by disc99** [comment]
> 運用はGit Flowで大丈夫？

一旦リリース前にマージするブランチが必要であればGit Flowでいいと思います！

ただGit Flowはリリースまでdevelopやreleaseブランチの経由する性質上、どうしてもコミュニケーションコストがかかるので、分かれて開発する今の状況であればGithub Flowで出来るだけそこのコストを省いて細かくリリースを繰り返すのもありかと思います！

**Comment by disc99** [comment]
> WBS欲しいかな。

気軽に使えるものがあるといいですね！
今はタスクも多くないですし、高機能なツールの使い方で時間を使うより、多少原始的なスタイルでもみんなは実装とか設計とか当初の目的に時間を使えたほうがいいかもしれません！

時間があればその辺の周辺ツールとかも探してみます！

**Comment by disc99** [comment]
> 時間があればその辺の周辺ツールとかも探してみます！

ひとまず少しまとめました！
https://github.com/javamas/araignee/wiki/Tools

**Comment by dodoichi** [comment]
おぉ、まとめありがとう！

CIはCircleCIに移る人が多い印象だったけど、比較を見る限り、TravisCIで良さそう。

Waffleのシンプルさは良いね。ZenHubで目玉になりそうな機能が出てこなければ、Waffleで行こうか。

追加で入れたいものとしては、以前話したSputnikを試してみたいな。TravisCI、CircleCIと連携してCheckStyleとかFindBugsのチェックを自動でやってくれる。
[Sputnik](https://sputnik.ci/) 

Git Worklowは、規模的にもGitHub Flowの方が向いてるかもね。

**Comment by dodoichi** [comment]
ZenHubの機能で目玉になりそうなもの
- 複数レポジトリを一つのカンバンに表示できる
- バーンダウンチャートを表示できる

かなり惹かれる。

**Comment by dodoichi** [comment]
ApiaryはMarkdownでAPIを開発できるのかな。
こんなのがあるんだね。

**Comment by disc99** [comment]
> Sputnik

ToolsのWikiに追加しました！

ZenHubはEpicなどの機能も追加されてたり、サービス的にも勢いがありそうなので試してみたいとこですが、多機能なので短時間でみんなが理解出来るよう一旦使い方講座を開いたほうがいいかもです！
実際私も機能を把握できていないですｗ

**Comment by dodoichi** [comment]
ZenHubお試し中。

Issue登録時に設定する項目が増えるけど、選択するだけなのでコストにはならないかな。
- Pipeline
  - New Issue
    
    登録時にデフォルトで選択される。
  - Backlog
    
    すぐにやる予定がなければこちら。
  - To Do
    
    すぐにやるならこちら。
  - In Progress
    
    手を付けたらこちら。
  - Done
    
    終わったらこちら。
- Estimate
  
  これはStory Pointの見積もりを入力するところだけど、別途説明が必要かも。
- Epics
  
  どのEpicに属すのか選択する。とはいえ、Epic作るほどのプロジェクトじゃないんだよね、今のところ。これも別途説明が必要かも。

Issueの状態がGitHubの一覧だとわかりにくいので、やっぱりカンバンがあると便利。

各項目をちゃんと設定しておけば、自分たちがどのくらい頑張ったかバーンダウンチャートで表示してくれるので、次回MTGくらいから使いはじめるのがいいと思います。

Labelに"In Progress"っていうのがあって、Pipelineの同じものと丸かぶりしてるんだけど、Labelで進捗管理とかしないので、消しましょう。

**Comment by disc99** [comment]
説明ありがとうございます！

僕も使ってみた感じ導入の方向でいいと思います！
Estimate、Epicsは確かに事前知識が無いと分かりにくいので一度話し合ったほうがいいと気がします！

ちなみにLabelの"In Progress"はWaffleのカンバン内で移動させると自動的につくやつなので、ZenHubでいくのであれば削除で大丈夫ですね。

**Comment by dodoichi** [comment]
[ZenHubについて](https://github.com/javamas/araignee/wiki/ZenHub%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)を記載。

**Comment by dodoichi** [comment]
未定のものは別Issueを切ったので、このIssueはcloseします。
